[book]
title="You don't know ServiceNow APIs"
authors = ["Vishal Ingle"]
language = "en"
multilingual = false
src = "src"

[output.html.playground]
editable = true

[output.html]
mathjax-support = true

[output.html.code.hidelines]
javascript = "//"
